### ISSUE TITLE
Feedback for feature isnt working

### ISSUE THREAD

**Issue by faizan6557** [NeshOfficial/ai-bot#19]
### Description

The setup instructions mention installing the @ai-sdk/anthropic module with npm i @ai-sdk/anthropic, but it doesn't specify if any additional configurations are required after installation.

### Code example

npm i @ai-sdk/anthropic

**Comment by rehan985** [comment]
Hello,

Thank you for bringing this up. After installing the @ai-sdk/anthropic module using npm i @ai-sdk/anthropic, no further configuration is necessary. You can proceed by importing the module into your project as per the documentation. Should you need further assistance, feel free to reach out.

Best regards
