### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/ai-bot#22]
this code is not working due to some dependencies

The current codebase fails to run due to unresolved dependencies. The dependencies are not listed in the documentation, making it difficult to install them correctly. Additionally, the code throws errors when trying to execute certain functions.

how to resolve

**Comment by Muhammad-Awab** [comment]
Adding the missing dependencies to the `dependencies.conf` file. Updated the installation steps in the documentation to include specific commands for installing dependencies: `sudo apt-get install -f dependencies.conf`. The code now runs successfully, and all functions execute without errors. Please pull the latest changes, install dependencies, and test.
