### ISSUE TITLE
Code issue & dependency

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/ai-bot#44]
### Description

Hello,

In this test-gpt-2.py file some missing dependency also some code is not defined
name 'generate_difficult_filename' is not defined

### Code example

def write_lines_to_file(filename, num_lines=50):
with open(filename, 'w') as file:

**Comment by Muhammad-Awab** [comment]
pip install filename_generator

here is the complete code which you want

from filename_generator import generate_difficult_filename

def write_lines_to_file(filename, num_lines=50):
with open(filename, 'w') as file:
for i in range(1, num_lines + 1):
file.write(f'This is line number {i}\n')

difficult_filename = generate_difficult_filename()
